import {
    faUser,
    faStar,
    faCat,
    faDog,
    faCrow,
    faDragon,
    faGhost,
    faHatWizard,
    faGear,
    faMountainSun,
    faDumbbell,
    faHatCowboy,
    faHorseHead,
    faJetFighter,
    faSkull,
    faPizzaSlice,
    faFire,
    faLemon,
    faFeather,
    faLeaf,
    faSeedling,
    faMicrochip,
    faBoltLightning,
    faLocationCrosshairs,
    faMeteor,
    faSplotch
} from "@fortawesome/free-solid-svg-icons";

export const AvatarIcons = {
    user: faUser,
    star: faStar,
    cat: faCat,
    dog: faDog,
    crow: faCrow,
    dragon: faDragon,
    ghost: faGhost,
    wizardHat: faHatWizard,
    gear: faGear,
    mountainSun: faMountainSun,
    dumbbell: faDumbbell,
    hatCowboy: faHatCowboy,
    horseHead: faHorseHead,
    jetFighter: faJetFighter,
    skull: faSkull,
    pizzaSlice: faPizzaSlice,
    fire: faFire,
    lemon: faLemon,
    feather: faFeather,
    leaf: faLeaf,
    seedling: faSeedling,
    microchip: faMicrochip,
    boltLightning: faBoltLightning,
    locationCrosshairs: faLocationCrosshairs,
    meteor: faMeteor,
    splotch: faSplotch
};