import {
    faUser,
    faStar,
    faCat,
    faCrow,
    faDragon,
    faGhost,
    faHatWizard,
    faGear,
    faMountainSun,
    faDumbbell,
    faHatCowboy,
    faHorseHead,
    faJetFighter,
    faSkull,
    faPizzaSlice,
    faFire,
    faLemon,
    faFeather,
    faLeaf,
    faSeedling,
    faMicrochip,
    faBoltLightning,
    faLocationCrosshairs,
    faMeteor,
    faSplotch,
    faEye,
    faMusic,
    faGamepad,
    faGauge,
    faBatteryFull
} from "@fortawesome/free-solid-svg-icons";

export const AvatarIcons = {
    user: faUser,
    star: faStar,

    cat: faCat,
    crow: faCrow,
    horseHead: faHorseHead,
    dragon: faDragon,

    ghost: faGhost,
    wizardHat: faHatWizard,
    skull: faSkull,
    hatCowboy: faHatCowboy,

    pizzaSlice: faPizzaSlice,
    lemon: faLemon,
    leaf: faLeaf,
    feather: faFeather,

    fire: faFire,
    seedling: faSeedling,
    mountainSun: faMountainSun,
    meteor: faMeteor,

    gear: faGear,
    dumbbell: faDumbbell,
    microchip: faMicrochip,
    jetFighter: faJetFighter,

    locationCrosshairs: faLocationCrosshairs,
    splotch: faSplotch,
    eye: faEye,
    music: faMusic,

    gamepad: faGamepad,
    gauge: faGauge,
    batteryFull: faBatteryFull,
    boltLightning: faBoltLightning,
};
